### ISSUE TITLE
Add styles to the end of the StyleSheet, not to the beginning?

### ISSUE THREAD

**Issue by matude** [pSapien/vscode-react-native-move-styles#3]
Hi,

Currently all new styles are added to the top of the StyleSheet. Is there any way to change it so that all new items get added to the bottom of the StyleSheet, as last? This would follow more naturally how stylesheets are usually set up. Perhaps editing some config somewhere?

Otherwise a superb extension, thank you for making it!

**Comment by pSapien** [comment]
@matude 
The extension has been updated to `0.0.3`, which includes the feature allowing users to choose where to insert the new styles.
Do update the extension and check the README.

You could include this setting in your settings.json file to fix the issue.

```
"react-native-move-styles.insertOrder": "end"
```

https://marketplace.visualstudio.com/items?itemName=sapien.react-native-move-styles

Thanks for using the extension. Much appreciated.

**Comment by matude** [comment]
Oooh nice, superb, thank you very much!
